youtuber_info = {
    'albert dyrlund': "Dansk YouTuber kendt for sine komiske videoer og musik.",
    'an autistic psychologist': "YouTube-kanal, der fokuserer på bevidsthed og uddannelse om autisme.",
    'anas': "Dansk indholdsskaber kendt for vlogs og udfordringer.",
    'aqua': "Populær dansk YouTuber med fokus på underholdning og sjove videoer.",
    'archimo': "Dansk YouTuber kendt for gaming og Let's Play videoer.",
    'atilla ateş': "Dansk YouTuber med fokus på livsstil og rejseindhold.",
    'bananamin': "Dansk YouTuber kendt for kreativt indhold og videoer om kunst og DIY.",
    'big mathis': "YouTuber fra Danmark, der fokuserer på gaming og Minecraft-indhold.",
    'bjorn tv': "Dansk YouTuber med fokus på gaming og vlogs.",
    'bokoen1': "Dansk YouTuber kendt for sit gamingindhold og Let's Play videoer.",
    'brackeys': "Dansk gaming-YouTuber kendt for sin fokus på spiludvikling og tutorials.",
    'brainiac75': "Dansk YouTuber med fokus på videnskabelige eksperimenter og opdagelser.",
    'chino': "Dansk YouTuber med forskelligt indhold, herunder vlogs og udfordringer.",
    'clara kraft': "Dansk makeup-YouTuber kendt for skønheds- og modeindhold.",
    'crainer': "Dansk gamer og YouTuber kendt for Minecraft-indhold og sjove udfordringer.",
    'electrydragonite': "Dansk YouTuber fokuseret på Pokémon-indhold og spilvideoer.",
    'emil macko': "Dansk YouTuber og spiludvikler kendt for skræmmende spil og horrorindhold.",
    'f.c. københavn': "Officiel YouTube-kanal for fodboldklubben F.C. København.",
    'felix sr': "Dansk YouTuber med fokus på gaming og Fortnite-indhold.",
    'fie laursen': "Dansk YouTuber og influencer kendt for skønheds- og livsstilsindhold.",
    'fries': "Dansk YouTuber med kreativt indhold og videoer om kunst og DIY.",
    'gears for breakfast': "Dansk spiludvikler og YouTuber, skaberen af A Hat in Time.",
    'gus1thego': "Dansk gaming-YouTuber kendt for Minecraft-indhold og vlogs.",
    'hartvigen': "Dansk YouTuber med fokus på lifestyle- og modeindhold.",
    'iasmina edina': "Dansk YouTuber kendt for skønheds- og makeupindhold.",
    'jameskii': "Dansk YouTuber kendt for humoristiske videoer og satire.",
    'jayco': "Dansk musik-YouTuber kendt for musikcovers og originale sange.",
    'jens the beast': "Dansk YouTuber kendt for gaming og vlogs.",
    'kakio': "Dansk YouTuber kendt for Minecraft- og gamingindhold.",
    'kristine sloth': "Dansk YouTuber kendt for skønhedsindhold og vlogs.",
    'lasse vestergaard': "Dansk YouTuber kendt for sit comedy-indhold og sketches.",
    'learn how to dance': "Dansk danse-YouTuber med fokus på danseundervisning og tutorials.",
    'lego': "Officiel kanal for LEGO Group med videoer om LEGO-produkter og -byggeri.",
    'louliving': "Dansk bolig- og livsstils-YouTuber kendt for indretning og DIY-indhold.",
    'lukas graham': "Officiel musikvideoer og sange fra det danske band Lukas Graham.",
    'magmamusen': "Dansk Minecraft-YouTuber kendt for tutorials og kreativt indhold.",
    'meimei': "Dansk YouTuber kendt for vlogs og underholdende videoer.",
    'merryweather media': "Dansk YouTuber med fokus på tech og spilindhold.",
    'metallica': "Officiel musikvideoer og sange fra det legendariske metalband Metallica.",
    'michael novak': "Dansk YouTuber kendt for skægge og underholdende videoer.",
    'mvh dk': "Dansk YouTuber med forskelligt indhold, herunder vlogs og udfordringer.",
    'nadbash': "Dansk YouTuber kendt for musik og kreativt indhold.",
    'nadiaxel': "Dansk YouTuber kendt for skønheds- og livsstilsindhold.",
    'nicimakiclips': "Dansk gaming-YouTuber kendt for Minecraft-indhold.",
    'nomis the habitable super earth': "Dansk YouTuber med fokus på gaming og vlogs.",
    'nordic animism': "Dansk YouTuber kendt for indhold om nordisk animisme og spiritualitet.",
    'obf': "Dansk YouTuber kendt for gaming og underholdende videoer.",
    'oliver street': "Dansk YouTuber med fokus på gaming og vlogs.",
    'playaphonk': "Dansk musik-YouTuber kendt for phonomusic og musikmixer.",
    'pursued': "Dansk gaming-YouTuber kendt for Minecraft-indhold og vlogs.",
    'revy redfox': "Dansk YouTuber kendt for humoristiske videoer og sketches.",
    'robinkaja': "Dansk YouTuber kendt for gaming- og vlogsindhold.",
    'shork': "Dansk gaming-YouTuber kendt for Fortnite-indhold og vlogs.",
    'sif avellana': "Dansk YouTuber kendt for makeup- og skønhedsindhold.",
    'sim dane': "Dansk YouTuber kendt for vlogs og rejseindhold.",
    'sir spooks': "Dansk YouTuber kendt for skræmmende og uhyggelige historier.",
    'spaghetti road': "Dansk YouTuber med fokus på madlavning og opskrifter.",
    'ssethtzeentach': "Dansk gaming-YouTuber kendt for anmeldelser og Let's Play videoer.",
    'stanleymov': "Dansk YouTuber kendt for gaming og underholdende videoer.",
    'surfshark academy': "Dansk YouTuber med fokus på online sikkerhed og privatliv.",
    'sybo tv': "Officiel kanal for spiludvikleren SYBO med indhold om Subway Surfers.",
    't b skyen': "Dansk gaming-YouTuber kendt for analyser og gamingindhold.",
    'that dane': "Dansk YouTuber med forskelligt indhold, herunder vlogs og sjove videoer.",
    'thea gaming': "Dansk gaming-YouTuber kendt for Let's Play og spilrelateret indhold.",
    'uberdanger': "Dansk YouTuber kendt for humoristiske videoer og underholdning.",
    'unity': "Officiel kanal for Unity Technologies med videoer om spiludvikling.",
    'volttheofficial': "Dansk YouTuber kendt for gaming- og underholdningsindhold.",
    'wawor': "Dansk YouTuber kendt for gaming og vlogs.",
    'yung spinach': "Dansk YouTuber kendt for musik og kreativt indhold.",
    'zagimc': "Dansk Minecraft-YouTuber kendt for gameplay og tutorials.",
    'ourwaytogame': "OurWayToGame er to danske gaming youtubere, der også er kendt som jepperdebber. aka jeppe og mikkel. de laver videoer omkring minecraft, fortnite, among us og andre spil.",
    'mrbreast': "Mente du MrBeast?",
    't-series': "Indisk musikvideo-kanal og pladeselskab.",
    'cocomelon - nursery rhymes': "Amerikansk YouTube-kanal og streamingmedieshow.",
    'set india': "Indisk YouTube-kanal med forskellige shows og serier.",
    'pewdiepie': "Svensk YouTuber kendt for Let's Play og humoristisk indhold.",
    'mrbeast': "Amerikansk YouTuber kendt for filantropiske stunts og udfordringer.",
    'like nastya': "Amerikansk-russisk YouTuber kendt for børnevideoer.",
    'kids diana show': "Amerikansk-russisk YouTuber kendt for børneindhold.",
    'zee music company': "Indisk musikpladeselskab og kanal.",
    'wwe': "Officiel YouTube-kanal for WWE (World Wrestling Entertainment).",
    'vlad and niki': "Russisk-amerikansk YouTube-kanal med to unge brødre.",
    'blackpink': "Officiel YouTube-kanal for den sydkoreanske pigegruppe BLACKPINK.",
    'goldmines': "Indisk YouTube-kanal med film og underholdning.",
    'justin bieber': "Canadisk sanger-songwriters officielle YouTube-kanal.",
    'sony sab': "Indisk tv-kanals officielle YouTube-kanal.",
    'bangtantv': "Officiel YouTube-kanal for den sydkoreanske gruppe BTS.",
    'hybe labels': "Officiel YouTube-kanal for den sydkoreanske underholdningsvirksomhed HYBE.",
    'canal kondzilla': "Brasiliansk musikvideo-producentens officielle YouTube-kanal.",
    'zee tv': "Indisk tv-kanals officielle YouTube-kanal.",
    'shemaroo filmi gaane': "Indisk musik- og film-YouTube-kanal.",
    'colors tv': "Indisk tv-kanals officielle YouTube-kanal.",
    'chuchu tv nursery rhymes & kids songs': "Indisk børneunderholdnings-YouTube-kanal.",
    'dude perfect': "Amerikansk sports- og underholdnings-YouTube-kanal.",
    'movieclips': "Amerikansk YouTube-kanal med filmklip og trailers.",
    'pinkfong baby shark - kids\' songs & stories': "Amerikansk YouTube-kanal med børnesange og fortællinger.",
    'tips official': "Indisk musikpladeselskabs officielle YouTube-kanal.",
    'marshmello': "Amerikansk elektronisk musikproducent og performer.",
    'wave music': "Indisk musikpladeselskab og kanal.",
    'sony music india': "Indisk musikpladeselskab og kanal.",
    'aaj tak': "Indisk nyhedsmedie og kanal.",
    'el reino infantil': "Spansk YouTube-kanal med børneindhold.",
    'ed sheeran': "Engelsk singer-songwriter og musiker.",
    'ariana grande': "Amerikansk sanger og skuespiller.",
    'eminemmusic': "Amerikansk rapper og musiker.",
    't-series bhakti sagar': "Indisk YouTube-kanal med spirituelt og religiøst indhold.",
    'looloo kids - nursery rhymes and children\'s songs': "Amerikansk YouTube-kanal med børnesange og fortællinger.",
    'taylor swift': "Amerikansk singer-songwriter og musiker.",
    'bad bunny': "Puertoricansk sanger og rapper.",
    'você sabia?': "Brasiliansk YouTube-kanal med faktavideoer og interessante oplysninger.",
    'alan walker': "Norsk-britisk producer og DJ.",
    'like nastya show': "Amerikansk-russisk YouTube-kanal med børneindhold.",
    'abs-cbn entertainment': "Filippinsk underholdningskanal.",
    'shemaroo': "Indisk YouTube-kanal med film- og underholdningsindhold.",
    'speed records': "Indisk musikpladeselskab og kanal.",
    'carryminati': "Indisk YouTuber kendt for komedie og roasts.",
    'elrubiusomg': "Spansk YouTuber kendt for gamingindhold.",
    'little baby bum - nursery rhymes & kids songs': "Amerikansk YouTube-kanal med børnesange og fortællinger.",
    'voot kids': "Indisk YouTube-kanal med børneindhold.",
    'маша и медведь': "Russisk YouTube-kanal med animationsindhold.",
    'luccas neto - luccas toon': "Brasiliansk YouTube-kanal med børneindhold.",
    'luisito comunica': "Mexicansk YouTuber kendt for rejseindhold.",
    'ishtar music': "Indisk musikpladeselskab og kanal.",
    'theellenshow': "Amerikansk TV-vært og producents officielle YouTube-kanal.",
    'toys and colors': "Amerikansk YouTube-kanal med børneindhold.",
    'kimberly loaiza': "Mexicansk YouTuber og sangerinde.",
    'workpointofficial': "Thailandsk underholdningskanal.",
    'xxxtentacion': "Amerikansk rapper og musiker.",
    'super simple songs - kids songs': "Canadisk YouTube-kanal med børnesange og fortællinger.",
    'shakira': "Colombiansk sangerinde og musiker.",
    'gr6 explode': "Brasiliansk YouTube-kanal med musikindhold.",
    'daddy yankee': "Puertoricansk reggaeton-artist og musiker.",
    'shfa': "Forenede Arabiske Emirater-baseret YouTuber.",
    'ช่อง one31': "Thailandsk TV-kanals officielle YouTube-kanal.",
    'shfa2 - شفا': "Forenede Arabiske Emirater-baseret YouTuber.",
    'goldmines gaane sune ansune': "Indisk musikpladeselskab og kanal.",
    'tedx talks': "Officielle TEDx-talks på YouTube.",
    'ozuna': "Puertoricansk reggaeton-artist og musiker.",
    'youtube': "Verdens største platform for deling af videoer.",
    'masha and the bear': "Russisk animations-tv-serie og YouTube-kanal.",
    'bruno mars': "Amerikansk sanger, sangskriver og musiker.",
    'jkk entertainment': "YouTuber kendt for musikindhold.",
    'maria clara & jp': "Brasiliansk YouTuber-par kendt for underholdning og vlogs.",
    't-series apna punjab': "Indisk musikpladeselskab og kanal.",
    'total gaming': "Indisk YouTuber kendt for gamingindhold.",
    'j balvin': "Colombiansk sanger og musiker.",
    'abp news': "Indisk nyhedsmedie og kanal.",
    'vegetta777': "Spansk YouTuber kendt for gamingindhold.",
    'markiplier': "Amerikansk YouTuber kendt for gamingindhold.",
    'desi music factory': "Indisk musikpladeselskab og kanal.",
    'nocopyrightsounds': "Engelsk pladeselskab kendt for musik uden ophavsret.",
    'geet mp3': "Indisk musikpladeselskab og kanal.",
    "ryan's world": "Amerikansk YouTube-kanal med børneindhold.",
    'bollywood classics': "Indisk musikpladeselskab og kanal.",
    'sony pal': "Indisk tv-kanals officielle YouTube-kanal.",
    'like nastya esp': "Spansk YouTube-kanal med børneindhold.",
    'la granja de zenón': "Argentinsk YouTube-kanal med børneindhold.",
    'mikecrack': "Spansk YouTuber kendt for gamingindhold.",
    'saregama music': "Indisk musikpladeselskab og kanal.",
    'rajshri': "Indisk musikpladeselskab og kanal.",
    'danish mastery': "YouTuber der laver videoer for alle niveauer. Hvis du er en fuldstændig nybegynder, eller du har allerede studeret dansk i et stykke tid.",
    'anders trust': "YouTuber der laver videoer om fitness.",
    'trendniq': "YouTuber der laver videoer om film og animation.",
    'xcifer': "YouTuber med 435 abonnenter og 15 views.",
    'robe trotting': "YouTuber med 8.7K abonnenter og 335 views.",
    'lucca på loftet': "YouTuber med 10.2K abonnenter og 307 views.",
    "travelin' young": "YouTuber der laver videoer om rejser og med 566 views.",
    '10 ud af 10': "YouTuber med 25K abonnenter og 804 views.",
    'lassebaekkelund': "YouTuber med 2.7K abonnenter og 111 views.",
    'wicked winks': "YouTuber der laver daglige vlogs med 38.9K views.",
    'jackie klink': "YouTuber med 396 views.",
    'imran nasir': "YouTuber med 2.7K abonnenter og 193 views.",
    'røde kors i danmark': "YouTuber der laver videoer om DIY & Life Hacks med 10.1K views.",
    'morten münster': "Morten Münster er en dansk forfatter, foredragsholder og ekspert inden for adfærdspsykologi og lederskab. Han er kendt for sit arbejde med at hjælpe enkeltpersoner og organisationer med at forstå menneskelig adfærd og motivation.",
    'knowix': "YouTuber der laver videoer om musik & dance og video spil med 16.3K views.",
    'türker alici': "YouTuber der har 0 views.",
    'anna munch': "YouTuber der har 1.1K views.",
    'bf lifestyle': "YouTuber der har 628 views.",
    'james køkken': "YouTuber der har 987 views.",
    'ripple': "YouTuber der har 123 views.",
    'dbu': "YouTuber der har 204 views.",
    'forsvaret': "YouTuber der har 394 views.",
    'arian planet': "YouTuber der har 20 views.",
    'amanda guldager': "YouTuber der har 54 views.",
    'robin che': "YouTuber der har 75 views.",
    'beduna': "YouTuber der har 191 views.",
    'ronnie skov': "YouTuber der har 431 views.",
    'engelengelife': "YouTuber der har 7 views.",
    'flying superkids': "YouTuber der har 17 views.",
    'jk2nd': "YouTuber der har 25 views.",
    'fodboldidioterne': "YouTuber der har 8 views.",
    'gram': "YouTuber der har 8 views.",
    'tivoli tv': "YouTuber der har 7 views.",
    'tabu tv': "YouTuber der har 6 views.",
    'cecilia demant': "YouTuber der har 14 views.",
    'tv 2 echo': "YouTuber der har 5 views.",
    'toucansss': "YouTuber der har 63 views.",
    'zebastian bach': "YouTuber der har 75 views.",
    'mia friis': "YouTuber der har 35 views.",
    'blockbuster': "YouTuber der har 0 views.",
    'tv2 østjylland': "YouTuber der har 10 views.",
    'dyb ro': "YouTuber der har 13 views.",
    'ronjajurs': "YouTuber der har 80 views.",
    'spørge jørgen': "YouTuber der har 16 views.",
    'champen dk': "YouTuber der har 0 views.",
    'michaels kælder': "YouTuber der har 0 views.",
    'this is petar': "YouTuber der har 6 views.",
    'tv2 nord': "YouTuber der har 0 views.",
    'daves highway': "YouTuber der har 2 views.",
    'robinsamse': "Robinsamse er en populær dansk YouTube-kanal, der gennem en kombination af gaming og virkelighedsbaseret indhold tiltrækker en bred vifte af seere. På kanalen deler Robin og Samrita, et par der er kærester i virkeligheden, deres oplevelser fra deres hverdage, mens de deltager i en række forskellige spil. Kanalen er kendt for sin letgenkendelige og humoristiske stil, der gør det til en sjov og afslappet oplevelse for seerne. De foretager sig en række forskellige aktiviteter på kanalen, herunder gaming, virkelighedsbaseret udfordringer og daglige vlogs. Robinsamse har opbygget en betydelig fanskare gennem deres engagerende indhold og deres åbne og hæderlige adfærd over for hinanden og deres seere. De er kendt for deres positive og inkluderende tilgang til deres seere, hvilket har bidraget til deres popularitet og succes på YouTube. Hvis du er interesseret i gaming, virkelighedsbaseret indhold eller bare ønsker at se et par, der deler deres liv med hinanden på en sjov og letgenkendelig måde, er Robinsamse en kanal der værder at følge.",
    'mrmastertop1': "MrMasterTop1. Er en dansk gaming youtuber, som for det meste laver videor, om minecraft. HAN ER HELT KLART MIN YNGLINGS YOUTUBERE!!!",
    'zeqodes': "ZeQodes er en dansk gaming youtuber, som for det meste laver videor, om minecraft. Han er også en af mine ynglings youtubers. Han har, blandt andet lavet min ynglings video EVER! Som er FINDER METTE FREDRIKSENS HEMMELIGE BASE! - Minecraft",
    'charlie2game': "Charlie2game er en dansk youtuber, han laver videor, om minecraft. Også kendt som Charlie, som også er aktiv på denne server. Han er en lille youtuber han har 48 subs og laver minecraft videoer",
    'instanbulleren': "SKYD DIG SELV I HOVEDET! - Minecraft",
    'ppgamingdk': "PPGamingDK også kendt som Phillip Eis, dog tror han selv at han hedder Phillip Smith! Han spiller FiveM og andre spil + han er destruktiv, i følge mig selv.",
    'kakao_dk': "Kakao_DK er en dansk youtuber, der laver IRL videoer, han har blandt andet været i diss-track battle med Gitcor",
    'gud': "Gud er den mest geniale AI-programmør, og han brugte python 🐍. No cap frfr, on god, bogstavligt talt, frfr, jk... unless? 😏",
    'satan': "Satan er den udfordrende spiltester, der altid prøver at distrahere os fra at nå vores mål i det kosmiske computerspil. Gud og Satan spiller et episk spil af strategi og moral, og vi er midt i det hele som spilfigurer, der skal navigere gennem dette digitale univers.",
    'jesus': "Jesus var ligesom en intergalaktisk superhelt, der fløj rundt på en regnbue-pony og spiste glitrende enhjørningskager til morgenmad. Han havde en hel arsenal af mystiske kræfter, som at forvandle vand til boblende limonade og lade fisk synge opera. Hans yndlingshobby var at spille tag i skyerne med englene og tage selfies med stjernerne.",
    'buddha': "Buddha var en slags superhelt, der kunne gøre alt, hvad han ville, fordi han havde opdaget, at han var en del af det store univers. Han var en slags superhelt, der kunne gøre alt, hvad han ville, fordi han havde opdaget, at han var en del af det store univers. Han var en slags superhelt, der kunne gøre alt, hvad han ville, fordi han havde opdaget, at han var en del af det store univers.",
    'muhammad': "Undskyld, men kan desværre ikke, svare på dit spørgsmål. Prøv /hvem_er Jesus",
    'istanbulleren': "Istanbulleren er en crazy damme, ved navn Alberte fra Istanbul, der jonglerer med kebabs og drager på æventyr med en flyvende tæppe-surfbrætshybrid! 🌯🪑✨",
    'tierrg': "Tierrg er en dansk gaming-youtuber, der primært fokuserer på at skabe indhold om Minecraft og GTA 5.",
    'hitler': "Adolf Hitler var en tysk diktator og leder af nazipartiet. Han førte Tyskland ind i Anden Verdenskrig og stod bag Holocaust, hvor millioner blev myrdet. Hitler begik selvmord i 1945 efter Tysklands nederlag.",
    'adolf hitler': "Adolf Hitler var en tysk diktator og leder af nazipartiet. Han førte Tyskland ind i Anden Verdenskrig og stod bag Holocaust, hvor millioner blev myrdet. Hitler begik selvmord i 1945 efter Tysklands nederlag.",
    'stalin': "Josef Stalin var en sovjetisk diktator og leder af Sovjetunionen. Han var en af de mest magtfulde og skræmmende ledere i det 20. århundrede. Han var ansvarlig for millioner af dødsfald og var en af de mest brutale diktatorer i historien.",
    'josef stalin': "Josef Stalin var en sovjetisk diktator og leder af Sovjetunionen. Han var en af de mest magtfulde og skræmmende ledere i det 20. århundrede. Han var ansvarlig for millioner af dødsfald og var en af de mest brutale diktatorer i historien.",
    'kim jong-un': "Kim Jong-un er den nuværende leder af Nordkorea. Han er den tredje leder af den kommunistiske nation og har været ved magten siden 2011. Han er kendt for at være en brutal diktator, der har undertrykt sit folk og truet med at bruge atomvåben mod sine fjender.",
    'kim jong un': "Kim Jong-un er den nuværende leder af Nordkorea. Han er den tredje leder af den kommunistiske nation og har været ved magten siden 2011. Han er kendt for at være en brutal diktator, der har undertrykt sit folk og truet med at bruge atomvåben mod sine fjender.",
    'kim jong il': "Kim Jong-il var den anden leder af Nordkorea. Han var en brutal diktator, der undertrykte sit folk og truede med at bruge atomvåben mod sine fjender. Han var kendt for at være en af de mest brutale diktatorer i historien.",
    'kim jong-il': "Kim Jong-il var den anden leder af Nordkorea. Han var en brutal diktator, der undertrykte sit folk og truede med at bruge atomvåben mod sine fjender. Han var kendt for at være en af de mest brutale diktatorer i historien.",
    'kim il sung': "Kim Il-sung var den første leder af Nordkorea. Han var en brutal diktator, der undertrykte sit folk og truede med at bruge atomvåben mod sine fjender. Han var kendt for at være en af de mest brutale diktatorer i historien.",
    'kim il-sung': "Kim Il-sung var den første leder af Nordkorea. Han var en brutal diktator, der undertrykte sit folk og truede med at bruge atomvåben mod sine fjender. Han var kendt for at være en af de mest brutale diktatorer i historien.",
    # 'benito mussolino': "Benito Mussolini var en italiensk diktator og leder af det fascistiske parti. Han var en af de mest magtfulde og skræmmende ledere i det 20. århundrede. Han var ansvarlig for millioner af dødsfald og var en af de mest brutale diktatorer i historien.",
    'benito mussolini': "Benito Mussolini var en italiensk diktator og leder af det fascistiske parti. Han var en af de mest magtfulde og skræmmende ledere i det 20. århundrede. Han var ansvarlig for millioner af dødsfald og var en af de mest brutale diktatorer i historien.",
    'franklin d. roosevelt': "Franklin D. Roosevelt var den 32. præsident i USA..",
    'franklin d roosevelt': "Franklin D. Roosevelt var den 32. præsident i USA.",
    'joe biden': "Joe Biden er en amerikansk politiker, der blev født den 20. november 1942. Han blev valgt som præsident i USA og tiltrådte embedet den 20. januar 2021. Biden er medlem af det Demokratiske Parti og har haft en lang politisk karriere, herunder tjeneste som senator for Delaware og som vicepræsident under præsident Barack Obama fra 2009 til 2017. Som præsident fokuserer Biden på en bred vifte af politiske spørgsmål, herunder sundhed, klimaforandringer, økonomi og udenrigspolitik.",
    'donald trump': "Donald Trump er en amerikansk forretningsmand og politiker, der blev valgt som USA's præsident i 2017. Han er medlem af det Republikanske Parti og var yderst utilfreds med USA's, økonomi og udenrigspolitik under sin præsidentperiode. Trump er kendt for sin kontroversielle politik og hans brug af sociale medier til at kommunikere med offentligheden.",
    'barack obama': "Barack Obama er en amerikansk politiker, der blev født den 4. august 1961. Han er medlem af det Demokratiske Parti. Obama var USA's 44. præsident og tiltrådte embedet den 20. januar 2009. Han blev genvalgt for en anden periode i 2012 og tjente som præsident indtil januar 2017. Obama er kendt for sin historiske valgsejr som den første afroamerikanske præsident i USA. Hans præsidentperiode fokuserede på spørgsmål som sundhedspleje, økonomi og klimaforandringer.",
    'george bush': "George W. Bush er en amerikansk politiker, der blev født den 6. juli 1946. Han er medlem af det Republikanske Parti. Bush blev valgt som USA's 43. præsident og tiltrådte embedet den 20. januar 2001. Han blev genvalgt for en anden periode i 2004 og tjente som præsident indtil januar 2009. Hans præsidentperiode blev præget af begivenheder som angrebet den 11. september 2001, krigen mod terror, og invasionen af Irak i 2003. Bushs præsidentskab var også kendetegnet af indenrigspolitiske spørgsmål som skattereformer og uddannelse.",
    'bush': "George W. Bush er en amerikansk politiker, der blev født den 6. juli 1946. Han er medlem af det Republikanske Parti. Bush blev valgt som USA's 43. præsident og tiltrådte embedet den 20. januar 2001. Han blev genvalgt for en anden periode i 2004 og tjente som præsident indtil januar 2009. Hans præsidentperiode blev præget af begivenheder som angrebet den 11. september 2001, krigen mod terror, og invasionen af Irak i 2003. Bushs præsidentskab var også kendetegnet af indenrigspolitiske spørgsmål som skattereformer og uddannelse.",

#
        #LAND SECTION
    #######################################
       ################################
             #######################
                ##############
                    #####

    'andorra': "Det er et land, prøv /land 'andorra'",
    'albanien': "Det er et land, prøv /land 'albania'",
    'armenien': "Det er et land, prøv /land 'armenia'",
    'afganistan': "Det er et land, prøv /land 'afghanistan'",
    'algeriet': "Det er et land, prøv /land 'algeria'",
    'argentina': "Det er et land, prøv /land 'argentina'",
    'australien': "Det er et land, prøv /land 'australia'",
    'østrig': "Det er et land, prøv /land 'austria'",
    'aserbajdsjan': "Det er et land, prøv /land 'azerbaijan'",
    'bahamas': "Det er et land, prøv /land 'bahamas'",
    'bahrain': "Det er et land, prøv /land 'bahrain'",
    'bangladesh': "Det er et land, prøv /land 'bangladesh'",
    'barbados': "Det er et land, prøv /land 'barbados'",
    'hviderusland': "Det er et land, prøv /land 'belarus'",
    'belgien': "Det er et land, prøv /land 'belgium'",
    'belize': "Det er et land, prøv /land 'belize'",
    'benin': "Det er et land, prøv /land 'benin'",
    'bhutan': "Det er et land, prøv /land 'bhutan'",
    'bolivia': "Det er et land, prøv /land 'bolivia'",
    'bosnien-hercegovina': "Det er et land, prøv /land 'bosnia and herzegovina'",
    'botswana': "Det er et land, prøv /land 'botswana'",
    'brasilien': "Det er et land, prøv /land 'brazil'",
    'brunei': "Det er et land, prøv /land 'brunei'",
    'bulgarien': "Det er et land, prøv /land 'bulgaria'",
    'burkina faso': "Det er et land, prøv /land 'burkina faso'",
    'burundi': "Det er et land, prøv /land 'burundi'",
    'cambodja': "Det er et land, prøv /land 'cambodia'",
    'cameroon': "Det er et land, prøv /land 'cameroon'",
    'canada': "Det er et land, prøv /land 'canada'",
    'kap verde': "Det er et land, prøv /land 'cape verde'",
    'centralafrikanske republik': "Det er et land, prøv /land 'central african republic'",
    'tchad': "Det er et land, prøv /land 'chad'",
    'chile': "Det er et land, prøv /land 'chile'",
    'kina': "Det er et land, prøv /land 'china'",
    'colombia': "Det er et land, prøv /land 'colombia'",
    'comorerne': "Det er et land, prøv /land 'comoros'",
    'congo': "Det er et land, prøv /land 'congo'",
    'costa rica': "Det er et land, prøv /land 'costa rica'",
    'croatia': "Det er et land, prøv /land 'croatia'",
    'cuba': "Det er et land, prøv /land 'cuba'",
    'cypern': "Det er et land, prøv /land 'cyprus'",
    'tjekkiet': "Det er et land, prøv /land 'czech republic'",
    'danmark': "Det er et land, prøv /land 'denmark'",
    'djibouti': "Det er et land, prøv /land 'djibouti'",
    'dominica': "Det er et land, prøv /land 'dominica'",
    'dominikanske republik': "Det er et land, prøv /land 'dominican republic'",
    'østtimor': "Det er et land, prøv /land 'timor-leste'",
    'ecuador': "Det er et land, prøv /land 'ecuador'",
    'egypten': "Det er et land, prøv /land 'egypt'",
    'el salvador': "Det er et land, prøv /land 'el salvador'",
    'ækvatorialguinea': "Det er et land, prøv /land 'equatorial guinea'",
    'eritrea': "Det er et land, prøv /land 'eritrea'",
    'estland': "Det er et land, prøv /land 'estonia'",
    'eswatini': "Det er et land, prøv /land 'eswatini'",
    'etiopien': "Det er et land, prøv /land 'ethiopia'",
    'fiji': "Det er et land, prøv /land 'fiji'",
    'finland': "Det er et land, prøv /land 'finland'",
    'frankrig': "Det er et land, prøv /land 'france'",
    'gabon': "Det er et land, prøv /land 'gabon'",
    'gambia': "Det er et land, prøv /land 'gambia'",
    'georgien': "Det er et land, prøv /land 'georgia'",
    'tyskland': "Det er et land, prøv /land 'germany'",
    'ghana': "Det er et land, prøv /land 'ghana'",
    'grækenland': "Det er et land, prøv /land 'greece'",
    'grenada': "Det er et land, prøv /land 'grenada'",
    'guatemala': "Det er et land, prøv /land 'guatemala'",
    'guinea': "Det er et land, prøv /land 'guinea'",
    'guinea-bissau': "Det er et land, prøv /land 'guinea-bissau'",
    'guyana': "Det er et land, prøv /land 'guyana'",
    'haiti': "Det er et land, prøv /land 'haiti'",
    'honduras': "Det er et land, prøv /land 'honduras'",
    'ungarn': "Det er et land, prøv /land 'hungary'",
    'island': "Det er et land, prøv /land 'iceland'",
    'indien': "Det er et land, prøv /land 'india'",
    'indonesien': "Det er et land, prøv /land 'indonesia'",
    'iran': "Det er et land, prøv /land 'iran'",
    'irak': "Det er et land, prøv /land 'iraq'",
    'irland': "Det er et land, prøv /land 'ireland'",
    'israel': "Det er et land, prøv /land 'israel'",
    'italien': "Det er et land, prøv /land 'italy'",
    'elfenbenskysten': "Det er et land, prøv /land 'ivory coast'",
    'jamaica': "Det er et land, prøv /land 'jamaica'",
    'japan': "Det er et land, prøv /land 'japan'",
    'jordan': "Det er et land, prøv /land 'jordan'",
    'kasakhstan': "Det er et land, prøv /land 'kazakhstan'",
    'kenya': "Det er et land, prøv /land 'kenya'",
    'kiribati': "Det er et land, prøv /land 'kiribati'",
    'nordkorea': "Det er et land, prøv /land 'north korea'",
    'sydkorea': "Det er et land, prøv /land 'south korea'",
    'kosovo': "Det er et land, prøv /land 'kosovo'",
    'kuwait': "Det er et land, prøv /land 'kuwait'",
    'kirgisistan': "Det er et land, prøv /land 'kyrgyzstan'",
    'laos': "Det er et land, prøv /land 'laos'",
    'letland': "Det er et land, prøv /land 'latvia'",
    'libanon': "Det er et land, prøv /land 'lebanon'",
    'lesotho': "Det er et land, prøv /land 'lesotho'",
    'liberia': "Det er et land, prøv /land 'liberia'",
    'libyen': "Det er et land, prøv /land 'libya'",
    'liechtenstein': "Det er et land, prøv /land 'liechtenstein'",
    'litauen': "Det er et land, prøv /land 'lithuania'",
    'luxembourg': "Det er et land, prøv /land 'luxembourg'",
    'madagascar': "Det er et land, prøv /land 'madagascar'",
    'malawi': "Det er et land, prøv /land 'malawi'",
    'malaysia': "Det er et land, prøv /land 'malaysia'",
    'maldiverne': "Det er et land, prøv /land 'maldives'",
    'mali': "Det er et land, prøv /land 'mali'",
    'malta': "Det er et land, prøv /land 'malta'",
    'marshalløerne': "Det er et land, prøv /land 'marshall islands'",
    'mauritania': "Det er et land, prøv /land 'mauritania'",
    'mauritius': "Det er et land, prøv /land 'mauritius'",
    'mexico': "Det er et land, prøv /land 'mexico'",
    'mikronesien': "Det er et land, prøv /land 'micronesia'",
    'moldova': "Det er et land, prøv /land 'moldova'",
    'monaco': "Det er et land, prøv /land 'monaco'",
    'mongoliet': "Det er et land, prøv /land 'mongolia'",
    'montenegro': "Det er et land, prøv /land 'montenegro'",
    'marokko': "Det er et land, prøv /land 'morocco'",
    'mozambique': "Det er et land, prøv /land 'mozambique'",
    'myanmar': "Det er et land, prøv /land 'myanmar'",
    'namibia': "Det er et land, prøv /land 'namibia'",
    'nauru': "Det er et land, prøv /land 'nauru'",
    'nepal': "Det er et land, prøv /land 'nepal'",
    'holland': "Det er et land, prøv /land 'netherlands'",
    'new zealand': "Det er et land, prøv /land 'new zealand'",
    'nicaragua': "Det er et land, prøv /land 'nicaragua'",
    'niger': "Det er et land, prøv /land 'niger'",
    'nigeria': "Det er et land, prøv /land 'nigeria'",
    'nordmakedonien': "Det er et land, prøv /land 'north macedonia'",
    'norge': "Det er et land, prøv /land 'norway'",
    'oman': "Det er et land, prøv /land 'oman'",
    'pakistan': "Det er et land, prøv /land 'pakistan'",
    'palau': "Det er et land, prøv /land 'palau'",
    'panama': "Det er et land, prøv /land 'panama'",
    'papua ny guinea': "Det er et land, prøv /land 'papua new guinea'",
    'paraguay': "Det er et land, prøv /land 'paraguay'",
    'peru': "Det er et land, prøv /land 'peru'",
    'filippinerne': "Det er et land, prøv /land 'philippines'",
    'polen': "Det er et land, prøv /land 'poland'",
    'portugal': "Det er et land, prøv /land 'portugal'",
    'qatar': "Det er et land, prøv /land 'qatar'",
    'rumænien': "Det er et land, prøv /land 'romania'",
    'rusland': "Det er et land, prøv /land 'russia'",
    'rwanda': "Det er et land, prøv /land 'rwanda'",
    'saint kitts og nevis': "Det er et land, prøv /land 'saint kitts and nevis'",
    'saint lucia': "Det er et land, prøv /land 'saint lucia'",
    'saint vincent og grenadinerne': "Det er et land, prøv /land 'saint vincent and the grenadines'",
    'samoa': "Det er et land, prøv /land 'samoa'",
    'san marino': "Det er et land, prøv /land 'san marino'",
    'sao tome og principe': "Det er et land, prøv /land 'sao tome and principe'",
    'saudi-arabien': "Det er et land, prøv /land 'saudi arabia'",
    'senegal': "Det er et land, prøv /land 'senegal'",
    'serbien': "Det er et land, prøv /land 'serbia'",
    'seychellerne': "Det er et land, prøv /land 'seychelles'",
    'sierra leone': "Det er et land, prøv /land 'sierra leone'",
    'singapore': "Det er et land, prøv /land 'singapore'",
    'slovakiet': "Det er et land, prøv /land 'slovakia'",
    'slovenien': "Det er et land, prøv /land 'slovenia'",
    'salomonøerne': "Det er et land, prøv /land 'solomon islands'",
    'somalia': "Det er et land, prøv /land 'somalia'",
    'sydafrika': "Det er et land, prøv /land 'south africa'",
    'sydsudan': "Det er et land, prøv /land 'south sudan'",
    'spanien': "Det er et land, prøv /land 'spain'",
    'sri lanka': "Det er et land, prøv /land 'sri lanka'",
    'sudan': "Det er et land, prøv /land 'sudan'",
    'surinam': "Det er et land, prøv /land 'suriname'",
    'sverige': "Det er et land, prøv /land 'sweden'",
    'schweiz': "Det er et land, prøv /land 'switzerland'",
    'syrien': "Det er et land, prøv /land 'syria'",
    'taiwan': "Det er et land, prøv /land 'taiwan'",
    'tadsjikistan': "Det er et land, prøv /land 'tajikistan'",
    'tanzania': "Det er et land, prøv /land 'tanzania'",
    'thailand': "Det er et land, prøv /land 'thailand'",
    'togo': "Det er et land, prøv /land 'togo'",
    'tonga': "Det er et land, prøv /land 'tonga'",
    'trinidad og tobago': "Det er et land, prøv /land 'trinidad and tobago'",
    'tunesien': "Det er et land, prøv /land 'tunisia'",
    'tyrkiet': "Det er et land, prøv /land 'turkey'",
    'turkmenistan': "Det er et land, prøv /land 'turkmenistan'",
    'tuvalu': "Det er et land, prøv /land 'tuvalu'",
    'uganda': "Det er et land, prøv /land 'uganda'",
    'ukraine': "Det er et land, prøv /land 'ukraine'",
    'forenede arabiske emirater': "Det er et land, prøv /land 'united arab emirates'",
    'storbritannien': "Det er et land, prøv /land 'united kingdom'",
    'usa': "Det er et land, prøv /land 'united states'",
    'uruguay': "Det er et land, prøv /land 'uruguay'",
    'usbekistan': "Det er et land, prøv /land 'uzbekistan'",
    'vanuatu': "Det er et land, prøv /land 'vanuatu'",
    'vatikanstaten': "Det er et land, prøv /land 'vatican city'",
    'venezuela': "Det er et land, prøv /land 'venezuela'",
    'vietnam': "Det er et land, prøv /land 'vietnam'",
    'yemen': "Det er et land, prøv /land 'yemen'",
    'zambia': "Det er et land, prøv /land 'zambia'",
    'zimbabwe': "Det er et land, prøv /land 'zimbabwe'",

}

########

